# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54b1030beda294cb84367f4fc417a7ed8e4220b583ace2dd585d9f56fe03f07e4a4693a3153e1c166e2087cd1d2c5a0a4a223a7f371d7bef7c5030e102fee7c3

test:
  secret_key_base: 2d647e35c034bff7739ebb1413acc5c53e0a74f24f5b5ec032c39c89f7deec25aad69d3b4682e6cc1571e1c74a91ab7ee2347cba4b51dc301d9c8cab27bc7c7d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
